# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false

cache:
  packages: true

r:
- release

apt_packages:
  - libglpk-dev

r_packages:
  - devtools
  - covr
  - pkgdown
  - lintr

r_github_packages:
  - sdcTools/ptable

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'library(lintr); lint_package(linters=with_defaults(line_length_linter(120), object_name_linter = NULL))'
  - Rscript -e 'covr::codecov()'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

notifications:
  email:
    on_success: always
    on_failure: always
