# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_get_max_contributions <- function(logicals_R, microdat_R, wvar_R, nv_R, top_k_in, n_threads) {
    .Call(`_cellKey_cpp_get_max_contributions`, logicals_R, microdat_R, wvar_R, nv_R, top_k_in, n_threads)
}

